### ISSUE TITLE
Using pylilv for plugin info (with checks) Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sone** [moddevices/mod-sdk#8]
Hello,

I've installed mod-sdk and mod-sdk-lv2 with KXStudio on Kubuntu 16.04 via Synaptic Package Manager and I get:

:~$ modsdk
Using pylilv for plugin info (with checks)
Segmentation fault (core dumped)

System log, Process: kernel:

[20820.977676] modsdk[18637]: segfault at 0 ip 00007f36dc63853b sp 00007ffdca3de110 error 4 in dssi.so[7f36dc636000+4000]

Kernel log:

2018-01-27 18:31 modsdk[18637] segfault at 0 ip 00007f36dc63853b sp 00007ffdca3de110 error 4 in dssi.so[7f36dc636000+4000]

I installed mod-sdk via git without success before and tried to remove it to see if the installation via apt-get is working . Maybe this has messed up the installation(s)? How to clean up and which version to use?

I have no idea right now how to debug. So if some would kindly give some information it is very much appreciated.

Cheers

**Comment by falkTX** [comment]
Crashing on dssi.so leads me to believe it's related to naspro bridges.
Please remove any packages from your system with "naspro" on the name, they are completely broken.
Things should work fine after that.

**Comment by sone** [comment]
yes in deed as you said things are working fine now after removing everything with "naspro" in the name - thank you very very much!

**Comment by falkTX** [comment]
thanks for confirming. this can be closed now I guess.

(naspro is known to be pretty crashy...)
